// flow-typed signature: a5d08eb5ee60cd495d3eb3b872563265
// flow-typed version: <<STUB>>/jooks_v^1.0.0/flow_v0.105.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jooks'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jooks' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jooks/Jooks' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jooks/Jooks.js' {
  declare module.exports: $Exports<'jooks/Jooks'>;
}
