// flow-typed signature: a7c9f6dc1be6433588ab5ecbd6962750
// flow-typed version: <<STUB>>/url-search-params-polyfill_v^7.0.0/flow_v0.105.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'url-search-params-polyfill'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'url-search-params-polyfill' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'url-search-params-polyfill/index' {
  declare module.exports: $Exports<'url-search-params-polyfill'>;
}
declare module 'url-search-params-polyfill/index.js' {
  declare module.exports: $Exports<'url-search-params-polyfill'>;
}
