// flow-typed signature: 111781fbe6dec798991c34d0dbcdba70
// flow-typed version: <<STUB>>/@babel/plugin-transform-destructuring_v^7.5.0/flow_v0.105.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/plugin-transform-destructuring'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/plugin-transform-destructuring' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@babel/plugin-transform-destructuring/lib' {
  declare module.exports: any;
}

// Filename aliases
declare module '@babel/plugin-transform-destructuring/lib/index' {
  declare module.exports: $Exports<'@babel/plugin-transform-destructuring/lib'>;
}
declare module '@babel/plugin-transform-destructuring/lib/index.js' {
  declare module.exports: $Exports<'@babel/plugin-transform-destructuring/lib'>;
}
