// flow-typed signature: 91af8c67a2b39f2a6408c35eb7467404
// flow-typed version: <<STUB>>/@testing-library/react-hooks_v^2.0.1/flow_v0.105.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@testing-library/react-hooks'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@testing-library/react-hooks' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@testing-library/react-hooks/lib' {
  declare module.exports: any;
}

declare module '@testing-library/react-hooks/src' {
  declare module.exports: any;
}

// Filename aliases
declare module '@testing-library/react-hooks/lib/index' {
  declare module.exports: $Exports<'@testing-library/react-hooks/lib'>;
}
declare module '@testing-library/react-hooks/lib/index.js' {
  declare module.exports: $Exports<'@testing-library/react-hooks/lib'>;
}
declare module '@testing-library/react-hooks/src/index' {
  declare module.exports: $Exports<'@testing-library/react-hooks/src'>;
}
declare module '@testing-library/react-hooks/src/index.js' {
  declare module.exports: $Exports<'@testing-library/react-hooks/src'>;
}
